// GET Tasks API
export const GET_TASKS_API = 'GET_TASKS_API';
export const GET_TASKS_API_LOADING = 'GET_TASKS_API_LOADING';

// ADD_TASK API
export const ADD_TASK_API = 'ADD_TASK_API';

// UPDATE_TASK API
export const UPDATE_TASK_API = 'UPDATE_TASK_API';

// DELETE_TASK API
export const DELETE_TASK_API = 'DELETE_TASK_API';
